PyGAD - Python Genetic Algorithm

In [2]:
pip install pygad

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 KB 754.5 kB/s eta 0:00:00


In [6]:
import pygad
y =f(w1:w6) = w1x1 + w2x2 + w3x3 + w4x4 + w5x5 + w6x6
where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7) and y=44
function_inputs = [4,-2,3.5,5,-11,-4.7]
desired_output = 44

SyntaxError: ignored

In [7]:
import numpy

# Parameter initialization 
genes = 2
chromosomes = 10
mattingPoolSize = 6
offspringSize = chromosomes - mattingPoolSize
lb = -5
ub = 5
populationSize = (chromosomes, genes)
generations = 3

#Population initialization
population = numpy.random.uniform(lb, ub, populationSize)

for generation in range(generations):
    print(("Generation:", generation+1))
    fitness = numpy.sum(population*population, axis=1)
    print("\npopulation")
    print(population)
    print("\nfitness calcuation")
    print(fitness)
    # Following statement will create an empty two dimensional array to store parents
    parents = numpy.empty((mattingPoolSize, population.shape[1]))

    # A loop to extract one parent in each iteration
    for p in range(mattingPoolSize):
        # Finding index of fittest chromosome in the population
        fittestIndex = numpy.where(fitness == numpy.max(fitness))
        # Extracting index of fittest chromosome
        fittestIndex = fittestIndex[0][0]
        # Copying fittest chromosome into parents array
        parents[p, :] = population[fittestIndex, :]
        # Changing fitness of fittest chromosome to avoid reselection of that chromosome 
        fitness[fittestIndex] = -1
    print("\nParents:")
    print(parents)

    # Following statement will create an empty two dimensional array to store offspring
    offspring = numpy.empty((offspringSize, population.shape[1]))
    for k in range(offspringSize):
         #Determining the crossover point
         crossoverPoint = numpy.random.randint(0,genes) 

         # Index of the first parent.
         parent1Index = k%parents.shape[0]

         # Index of the second.
         parent2Index = (k+1)%parents.shape[0]

         # Extracting first half of the offspring
         offspring[k, 0: crossoverPoint] = parents[parent1Index, 0: crossoverPoint]

         # Extracting second half of the offspring
         offspring[k, crossoverPoint:] = parents[parent2Index, crossoverPoint:]
    print("\nOffspring after crossover:")
    print(offspring)

    # Implementation of random initialization mutation. 
    for index in range(offspring.shape[0]):
        randomIndex = numpy.random.randint(1,genes)
        randomValue = numpy.random.uniform(lb, ub, 1)
        offspring [index, randomIndex] = offspring [index, randomIndex] + randomValue
    print("\n Offspring after Mutation")
    print(offspring)

    population[0:parents.shape[0], :] = parents
    population[parents.shape[0]:, :] = offspring
    print("\nNew Population for next generation:")
    print(population)

fitness = numpy.sum(population*population, axis=1)
fittestIndex = numpy.where(fitness == numpy.max(fitness))
# Extracting index of fittest chromosome
fittestIndex = fittestIndex[0][0]
# Getting Best chromosome
fittestInd = population[fittestIndex, :]
bestFitness = fitness[fittestIndex]
print("\nBest Individual:")

('Generation:', 1)

population
[[ 1.12411838 -1.51621319]
 [-4.33121784 -4.55992032]
 [-1.47416655  3.61966541]
 [ 3.83243091 -0.46470615]
 [ 0.65470549  1.5480023 ]
 [-1.41268376  4.22536247]
 [ 3.96860323 -0.7268284 ]
 [-0.05078393 -3.76829101]
 [-4.18280252 -1.64735013]
 [-3.34644757  2.11490735]]

fitness calcuation
[ 3.56254459 39.55232133 15.27514469 14.90347848  2.82495038 19.84936338
 16.27809111 14.20259618 20.20959937 15.67154444]

Parents:
[[-4.33121784 -4.55992032]
 [-4.18280252 -1.64735013]
 [-1.41268376  4.22536247]
 [ 3.96860323 -0.7268284 ]
 [-3.34644757  2.11490735]
 [-1.47416655  3.61966541]]

Offspring after crossover:
[[-4.18280252 -1.64735013]
 [-4.18280252  4.22536247]
 [-1.41268376 -0.7268284 ]
 [-3.34644757  2.11490735]]

 Offspring after Mutation
[[-4.18280252 -6.64426226]
 [-4.18280252  1.89747835]
 [-1.41268376  1.41067   ]
 [-3.34644757  3.73244742]]

New Population for next generation:
[[-4.33121784 -4.55992032]
 [-4.18280252 -1.64735013]
 [-1.41268376  4.2