In [1]:
import numpy as np
print(np.__version__)


1.22.4


In [3]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr = np.zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr = np.ones((3, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr = np.random.rand(3, 3)
arr


array([[0.64736394, 0.12931338, 0.41203264],
       [0.56673481, 0.58422857, 0.89504129],
       [0.16663606, 0.96244332, 0.04232253]])

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
print(arr.shape)


(2, 3)


In [12]:
print(arr.dtype)

int64


In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [15]:
print(arr[0])


1


In [16]:
print(arr[-1])


5


In [17]:
print(arr[1:4])

[2 3 4]


In [19]:
#Array Manipulation
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr_reshaped = arr.reshape((3, 2))
arr_reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
# Vertical stack
arr_v_stack = np.vstack([arr, arr])
arr_v_stack


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
arr_h_stack = np.hstack([arr, arr])
arr_h_stack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1+arr2)

[5 7 9]


In [29]:
print(arr1 - arr2)

[-3 -3 -3]


In [28]:
print(arr1 * arr2)

[ 4 10 18]


In [30]:
print(arr1 * arr2)


[ 4 10 18]


In [31]:
print(arr1 / arr2)


[0.25 0.4  0.5 ]


In [33]:
# Statistical Operation
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [34]:
print(np.mean(arr))


3.0


In [35]:
print(np.median(arr))

3.0


In [36]:
print(np.std(arr))


1.4142135623730951
